# Comment.

apple = 'pie'

number_array = [1, 2, 3]
string_array = ["a", 'b', '"c"']
mix_array = [[1, 2, 3], ["a", 'b', '"c"'], []]

[banana]
apple = 'juice'

[[cherry]]
color = 'red'

[[cherry]]
color = 'green'

[[cherry]]
color = 'blue'

[pinapple]
drink = 1

[pinapple.banana]
drink = 2

[pinapple.banana.cherry]
drink = 3

[[pinapple.banana.cherry.grape]]
drink = 4

[[pinapple.banana.cherry.grape]]
drink = 5

[[pinapple.banana.cherry.grape]]
drink = 6
