age = 40
weight = 93.5
apple = "pie"
adult = true
student = false

double_quoted_letter = "Hello, world!!"
triple_double_quoted_letter = """Hello,
world!!"""
single_quoted_letter = 'Hello, world!!'
triple_single_quoted_letter = '''Hello,
world!!'''

double_quoted_punctuation = "., ={}[]'\"\\!?"
triple_double_quoted_punctuation = """., ={}[]'"\\
!?"""
single_quoted_punctuation = '., ={}[]"\!?'
triple_single_quoted_punctuation = '''., ={}[]'"\
!?'''
