age = 40
weight = 93.5
apple = "pie"
adult = true
student = false

basic_strings_empty = ""
basic_strings_escape_backslash = "\\"
basic_strings_escape_double_quotation = "\""
basic_strings_letter = "Hello, world!!"
basic_strings_punctuation = "., ={}[]'\"\\!?"

multiline_basic_strings_letter = """Hello,
world!!"""
multiline_basic_strings_punctuation = """., ={}[]'"\\
!?"""
multiline_basic_strings_trim_start = """\
  The quick brown \
  fox jumps over \
  the lazy dog.\
  """

literal_strings_empty = ''
literal_strings_letter = 'Hello, world!!'
literal_strings_punctuation = '., ={}[]"\!?'

multiline_literal_strings_letter = '''Hello,
world!!'''
multiline_literal_strings_punctuation = '''., ={}[]'"\
!?'''
